# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudash < Formula
  desc "TUI dashboard for Claude Code — k9s-style sessions viewer"
  homepage "https://github.com/skofel1/claudash"
  version "1.6.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skofel1/homebrew-claudash/releases/download/v1.6.5/claudash_1.6.5_darwin_amd64.tar.gz"
      sha256 "ffbf02f4414fbed157d459a7c040e07cc265213fdaac2f27c7098154661c8982"

      define_method(:install) do
        bin.install "claudash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skofel1/homebrew-claudash/releases/download/v1.6.5/claudash_1.6.5_darwin_arm64.tar.gz"
      sha256 "b0b9ad9e60521a1f312babdb7ad80479ef98ba6d9d020fa8d5fc7dbc8d62b542"

      define_method(:install) do
        bin.install "claudash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skofel1/homebrew-claudash/releases/download/v1.6.5/claudash_1.6.5_linux_amd64.tar.gz"
      sha256 "a0251be9a9a6f6c8912b5ff0564f02d2310efda3b806e32dea0ceba38f7d0b6d"
      define_method(:install) do
        bin.install "claudash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skofel1/homebrew-claudash/releases/download/v1.6.5/claudash_1.6.5_linux_arm64.tar.gz"
      sha256 "b7116aae88a3ea82746ff0258cd64fb824a4efa69ef1fbbf38b02bd7f3cce0ae"
      define_method(:install) do
        bin.install "claudash"
      end
    end
  end

  test do
    system "#{bin}/claudash", "version"
  end
end
